
name: Damage Calculation Test

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      
      - run: ls
      - name: Install dependencies
        working-directory: ./workspace/ch4/damage-calc
        run: yarn install
        
      - name: Check directory
        working-directory: ./workspace/ch4/damage-calc
        run: ls
        
      - name: Install dependencies
        working-directory: ./workspace/ch4/damage-calc
        run: yarn install
      - name: Run test
        working-directory: ./workspace/ch4/damage-calc
        run: yarn test
      
